apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rudeshell
  name: rudeshell
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rudeshell
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rudeshell
    spec:
      containers:
      - image: shantnutiwari/rudeshell:v0-1
        name: rudeshell
        resources: {}
status: {}
