- hosts: all
  become: yes

  roles:
    - geerlingguy.docker

  tasks:


  - name: checkout repo
    become: no
    ansible.builtin.git:
      repo: 'https://github.com/shantnu/rudeshell.git'
      dest: /home/ubuntu/rudeshell

  - name: install packages
    apt: name={{item}} state=present
    with_items:
      - python3-pip
      # - python3-dev
      # - python3.8-venv

  - name: Install docker python package
    pip:
      name: docker

  - name: Create a volume
    community.docker.docker_volume:
      name: caddy_data